version: '3.8'

services:
  db:
    image: postgres:16
    container_name: auto_service_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auto_service
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data: